import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import "@/styles/globals.css";
import Provider from "@/components/Provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className="relative min-h-screen w-full bg-[url('/images/hero.jpg')] bg-no-repeat bg-center bg-fixed bg-cover flex flex-col justify-center items-center">
            <div className="absolute inset-0 bg-black/60 lg:bg-black/50 flex flex-col justify-center items-center p-4 w-full">
              <Navbar />
              {children}
            </div>
          </div>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
